[package]
name = "weather_bot_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = "0.7"
bytes = "1.0.1"
futures = "0.3.21"
tokio = { version = "0.2.22", features = ["full"] }
